services:
  - type: web
    name: doSport-backend
    env: java
    buildCommand: "cd doSports-server && ./mvnw clean package"
    startCommand: "java -jar doSports-server/target/*.jar"
    envVars:
      - key: JAVA_VERSION
        value: 17
